# Generated by Django 5.0.6 on 2024-06-17 10:18

import datetime
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doclogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=20)),
                ('Password', models.CharField(max_length=25)),
                ('Time', models.DateTimeField(default=datetime.datetime(2024, 6, 17, 15, 48, 26, 941727))),
            ],
        ),
        migrations.CreateModel(
            name='docreg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=20)),
                ('Password', models.CharField(max_length=25)),
                ('Confirm_Password', models.CharField(max_length=25)),
                ('Time', models.DateTimeField(default=datetime.datetime(2024, 6, 17, 15, 48, 26, 941727))),
            ],
        ),
        migrations.CreateModel(
            name='nurselogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=20)),
                ('Password', models.CharField(max_length=25)),
                ('Time', models.DateTimeField(default=datetime.datetime(2024, 6, 17, 15, 48, 26, 941727))),
            ],
        ),
        migrations.CreateModel(
            name='nursereg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=20)),
                ('Password', models.CharField(max_length=20)),
                ('Time', models.DateTimeField(default=datetime.datetime(2024, 6, 17, 15, 48, 26, 941727))),
            ],
        ),
        migrations.CreateModel(
            name='patientinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('Mobile', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
            ],
        ),
    ]
