# Generated by Django 5.0.6 on 2024-06-18 10:04

import datetime
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Mobile', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('Email', models.EmailField(max_length=254)),
                ('Message', models.TextField()),
                ('Time', models.DateTimeField(default=datetime.datetime(2024, 6, 18, 15, 34, 31, 331662))),
            ],
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='Department',
            field=models.CharField(choices=[('Cardio', 'Cardiology'), ('Neuro', 'Neurology'), ('Pedia', 'Pediatrician'), ('Ortho', 'Orthopedic'), ('General', 'General'), ('Onco', 'Oncology')], default=' ', max_length=7),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='Gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='O', max_length=1),
        ),
        migrations.AlterField(
            model_name='doclogin',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 18, 15, 34, 31, 316042)),
        ),
        migrations.AlterField(
            model_name='docreg',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 18, 15, 34, 31, 316042)),
        ),
        migrations.AlterField(
            model_name='nurselogin',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 18, 15, 34, 31, 316042)),
        ),
        migrations.AlterField(
            model_name='nursereg',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 18, 15, 34, 31, 316042)),
        ),
    ]
