# Generated by Django 5.0.6 on 2024-06-18 17:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_nursereg_confirmpassword_alter_doclogin_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doclogin',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 18, 23, 22, 16, 224155)),
        ),
        migrations.AlterField(
            model_name='docreg',
            name='Confirm_Password',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='docreg',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 18, 23, 22, 16, 224155)),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 18, 23, 22, 16, 224155)),
        ),
        migrations.AlterField(
            model_name='nurselogin',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 18, 23, 22, 16, 224155)),
        ),
        migrations.AlterField(
            model_name='nursereg',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 18, 23, 22, 16, 224155)),
        ),
    ]
