# Generated by Django 5.0.6 on 2024-06-18 18:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_doclogin_time_alter_docreg_confirm_password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='docreg',
            old_name='Confirm_Password',
            new_name='ConfirmPassword',
        ),
        migrations.AlterField(
            model_name='doclogin',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 18, 23, 42, 37, 432990)),
        ),
        migrations.AlterField(
            model_name='docreg',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 18, 23, 42, 37, 432990)),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 18, 23, 42, 37, 432990)),
        ),
        migrations.AlterField(
            model_name='nurselogin',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 18, 23, 42, 37, 432990)),
        ),
        migrations.AlterField(
            model_name='nursereg',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 18, 23, 42, 37, 432990)),
        ),
    ]
