# Generated by Django 5.0.6 on 2024-06-19 05:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_confirm_password_docreg_confirmpassword_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doclogin',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 19, 11, 5, 54, 208022)),
        ),
        migrations.AlterField(
            model_name='docreg',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 19, 11, 5, 54, 208022)),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='Mobile',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 19, 11, 5, 54, 208022)),
        ),
        migrations.AlterField(
            model_name='nurselogin',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 19, 11, 5, 54, 208022)),
        ),
        migrations.AlterField(
            model_name='nursereg',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 19, 11, 5, 54, 208022)),
        ),
    ]
