# Generated by Django 5.0.6 on 2024-06-19 12:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_patientinfo_time_alter_doclogin_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doclogin',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 19, 17, 54, 42, 406970)),
        ),
        migrations.AlterField(
            model_name='docreg',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 19, 17, 54, 42, 406970)),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='Email',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 19, 17, 54, 42, 422635)),
        ),
        migrations.AlterField(
            model_name='nurselogin',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 19, 17, 54, 42, 406970)),
        ),
        migrations.AlterField(
            model_name='nursereg',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 19, 17, 54, 42, 406970)),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 19, 17, 54, 42, 406970)),
        ),
    ]
