# Generated by Django 5.0.6 on 2024-06-19 12:36

import datetime
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_doclogin_time_alter_docreg_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doclogin',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 19, 18, 6, 48, 17444)),
        ),
        migrations.AlterField(
            model_name='docreg',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 19, 18, 6, 48, 17444)),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='Mobile',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 19, 18, 6, 48, 26991)),
        ),
        migrations.AlterField(
            model_name='nurselogin',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 19, 18, 6, 48, 17444)),
        ),
        migrations.AlterField(
            model_name='nursereg',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 19, 18, 6, 48, 17444)),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 19, 18, 6, 48, 17444)),
        ),
    ]
